services:
- type: web
  name: youbike-notify-bot
  env: node
  repo: https://github.com/chienniman/youbike-notify-bot.git
  buildCommand: npm install
  startCommand: node index.js
  plan: free
  autoDeploy: false
  envVars:
  - key: CHANNEL_ACCESS_TOKEN
    sync: false
  - key: CHANNEL_SECRET
    sync: false
